# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6910b949e19329419f9317a50cbfaf75d35005d0597e77cb04a4b318527f0ae8ecb38e3475d5ed0d87f153a39c4a73320f74f36ba5abd828258f02e2bc426d3

test:
  secret_key_base: 3f23fa9b81b08d7eb3fd9d8a6c94e7f242895a5f99c130257c76815a28edbed3e6beb54daf100a886a93db521f0fc1c2cd9b8c22e5513779cbbbc53d7e33b036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
